name: flutter_swiper_moolban
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6+5
homepage: https://github.com/rws08/flutter_swiper-moolban

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view: ^0.1.6
  flutter_page_indicator: ^0.0.3

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
